# Generated by Django 3.0.7 on 2020-06-29 13:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Agent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
                ('address', models.TextField()),
                ('phone1', models.TextField()),
                ('phone2', models.TextField()),
                ('email', models.TextField()),
                ('contact_person', models.TextField()),
                ('port', models.TextField()),
            ],
        ),
    ]
