# Generated by Django 3.0.7 on 2020-06-29 13:32

from django.db import migrations, models
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('testapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agent',
            name='address',
            field=models.CharField(max_length=300),
        ),
        migrations.AlterField(
            model_name='agent',
            name='contact_person',
            field=models.CharField(max_length=120),
        ),
        migrations.AlterField(
            model_name='agent',
            name='email',
            field=models.EmailField(max_length=254),
        ),
        migrations.AlterField(
            model_name='agent',
            name='name',
            field=models.CharField(max_length=120),
        ),
        migrations.AlterField(
            model_name='agent',
            name='phone1',
            field=phonenumber_field.modelfields.PhoneNumberField(max_length=128, region=None),
        ),
        migrations.AlterField(
            model_name='agent',
            name='phone2',
            field=phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=128, region=None),
        ),
        migrations.AlterField(
            model_name='agent',
            name='port',
            field=models.CharField(max_length=120),
        ),
    ]
