# Generated by Django 3.0.7 on 2020-06-29 13:40

from django.db import migrations, models
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('testapp', '0002_auto_20200629_1632'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('data', models.CharField(max_length=120)),
                ('certificate', models.CharField(max_length=120)),
                ('units', models.CharField(max_length=120)),
            ],
        ),
        migrations.CreateModel(
            name='Supplier',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('phone', phonenumber_field.modelfields.PhoneNumberField(max_length=128, region=None)),
                ('email', models.EmailField(max_length=254)),
                ('contact_person', models.CharField(max_length=120)),
                ('port_of_service', models.CharField(max_length=120)),
                ('payment_terms', models.CharField(max_length=120)),
            ],
        ),
    ]
